name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@v3.27.1 && echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run tests 
        run: |
          cd tests && make test
          
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/n0f4ph4mst3r/outbox-relay:latest
